/* Rewrite source references from .png/.jpg/.jpeg to .webp — but ONLY where
   the .webp actually exists in public/. Checking the filesystem rather than
   pattern-matching the path is what makes this safe to run: a reference to
   an image that was skipped (the PWA icons, og.png) or to one that never
   existed (/assets/about/*.png, which is already broken on main) is left
   exactly as it is, so this pass can shorten load time but cannot break a
   link that currently works.

   Run after scripts/to-webp.mjs. Idempotent — a second run finds nothing. */

import fs from 'node:fs'
import path from 'node:path'

const SRC_DIRS = ['src']
const EXT = /\.(jsx?|css|json)$/i

/* Generated by scripts/extract-content-images.mjs and gitignored with an
   explicit "never edit or commit" — rewriting it would be undone by the
   next `npm run prep` anyway. See the note in scripts/to-webp.mjs. */
const SKIP_FILES = [path.join('src', 'data', 'content.snapshot.built.json')]

const walk = (d) =>
  fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(d, e.name)
    return e.isDirectory() ? walk(p) : [p]
  })

const files = SRC_DIRS.flatMap(walk)
  .filter((f) => EXT.test(f))
  .filter((f) => !SKIP_FILES.includes(f))

/* matches a site-absolute image path inside quotes or url() */
const REF = /(\/[A-Za-z0-9_\-./ ]+?)\.(png|jpe?g)\b/g

let changedFiles = 0
let changedRefs = 0
const missing = new Set()

for (const file of files) {
  const before = fs.readFileSync(file, 'utf8')
  let hits = 0

  const after = before.replace(REF, (whole, stem, ext) => {
    /* leave anything that is not ours — a flagcdn.com URL's path also
       matches this shape, so the existence check on disk is what
       distinguishes them */
    const webpDisk = path.join('public', `${stem}.webp`)
    if (!fs.existsSync(webpDisk)) {
      if (!fs.existsSync(path.join('public', `${stem}.${ext}`))) missing.add(`${stem}.${ext}`)
      return whole
    }
    hits += 1
    return `${stem}.webp`
  })

  if (hits) {
    fs.writeFileSync(file, after)
    changedFiles += 1
    changedRefs += hits
    console.log(`  ${String(hits).padStart(3)} refs  ${file.replace(/\\/g, '/')}`)
  }
}

console.log(`\n${changedRefs} references across ${changedFiles} files → .webp`)

if (missing.size) {
  console.log(`\nleft alone — no file on disk under public/ (pre-existing):`)
  for (const m of [...missing].sort()) console.log(`  ${m}`)
}
